### ISSUE TITLE
python2.7-minimal is not enough on Debian Stretch

### ISSUE THREAD

**Issue by atkinsj** [zeek/zeek-docker#7]
The 2.5.5 Dockerfile does not function at the moment.
```
root@487779f2c450:/bro# broctl
Traceback (most recent call last):
  File "/bro/bin/broctl", line 13, in <module>
    from BroControl.broctl import BroCtl, BroControlError, CommandSyntaxError
  File "/usr/local/bro-2.5.5/lib/broctl/BroControl/broctl.py", line 8, in <module>
    from BroControl import lock
  File "/usr/local/bro-2.5.5/lib/broctl/BroControl/lock.py", line 4, in <module>
    from BroControl import config
  File "/usr/local/bro-2.5.5/lib/broctl/BroControl/config.py", line 9, in <module>
    from BroControl import py3bro
  File "/usr/local/bro-2.5.5/lib/broctl/BroControl/py3bro.py", line 26, in <module>
    from Queue import Queue, Empty
ImportError: No module named Queue
```

But:

```
root@487779f2c450:/bro# apt-get install python
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  bzip2 file libexpat1 libffi6 libmagic-mgc libmagic1 libpython-stdlib libpython2.7-stdlib libreadline7 libsqlite3-0 libssl1.1 mime-support python-minimal python2.7 readline-common xz-utils
Suggested packages:
  bzip2-doc python-doc python-tk python2.7-doc binutils readline-doc
The following NEW packages will be installed:
  bzip2 file libexpat1 libffi6 libmagic-mgc libmagic1 libpython-stdlib libpython2.7-stdlib libreadline7 libsqlite3-0 libssl1.1 mime-support python python-minimal python2.7 readline-common xz-utils
0 upgraded, 17 newly installed, 0 to remove and 0 not upgraded.
Need to get 5383 kB of archives.
After this operation, 21.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
[...]
root@487779f2c450:/bro# broctl -h
Hint: Run the broctl "deploy" command to get started.
Error: unknown command '-h'
```

I also get a `"mesg: ttyname failed: Inappropriate ioctl for device" ` when attempting to start the container but I haven't determined if that's related yet.

`Docker version 18.06.1-ce, build e68fc7a`

**Comment by JustinAzoff** [comment]
Ah, I never actually tried using broctl in the container - but I can swap out python-minimal for python2.7.  This likely affects all of the images, not just 2.5.5

**Comment by atkinsj** [comment]
Yup -- can confirm it goes back at least as far back as 2.3.1. It's not a huge deal as I'm using `FROM broplatform/bro:2.5.5` and installing it myself but it's probably worth changing.

Confirmed the ttyname issue was just me not issuing a -t on the run.

**Comment by RobertLarsen** [comment]
This is now the year 2020 and this error is still there. Also when using `/zeek/bin/zeekctl`.
